# Generated by Django 5.1.1 on 2024-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='universe',
            field=models.CharField(blank=True, choices=[('Marvel', 'Marvel'), ('DC', 'DC')], max_length=50, null=True),
        ),
    ]
